### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by vantu5z**
About tab is still untranslatable.

### CODE REVIEW

**Comment by Selenium-H** [comment]
> About tab is still untranslatable.

Sorry about that.

I've updated the `install_pot.sh` and `prefs.js` to include `About` tab translations.

**Comment by vantu5z** [comment]
Thanks! PR was rebased and updated.

Found another untranslatable place - at Profiles tab (Open, Close, Minimize, Unminimize)

**Comment by Selenium-H** [comment]
Updated `prefs.js` to translate the `Profiles Tab` properly.

**Comment by Selenium-H** [comment]
Thanks.

**Pull request merged**
